### ISSUE TITLE
[Bug]: $set on a currencyMask Input does not work

### ISSUE THREAD

**Issue by wdarins** [ariaieboy/filament-currency#11]
### What happened?

Whenever you try to set the value for a `currencyMask` input it does not work. If I remove `currencyMask` then `$set` is working.

### How to reproduce the bug

```php
TextInput::make('price'),
TextInput::make('quantity')
    ->live()
    ->afterStateUpdated(fn (Get $get, Set $set) => $set('total', $get('quantity') * $get('price')),
TextInput::make('total')->currencyMask(thousandSeparator: ',', decimalSeparator: '.', precision: 2),
```

### Package Version

1.1.3

### PHP Version

8.2.0

### Laravel Version

10.31.0

### Which operating systems does with happen with?

macOS

**Comment by ariaieboy** [comment]
duplicated of #9 fixed at 1.2.1
