### ISSUE TITLE
[Bug]: Masking on '$set' value seems to be broken still 

### ISSUE THREAD

**Issue by quinleys** [ariaieboy/filament-currency#31]
### What happened?

Thanks for looking into it this quickly! 
But same issue applies, nothing has changed for me. 
Maybe I can contact you directly, might be easier. 

As you can see, in the open section at the lower part of the screenshot. I got two fields 'Commission Makelaar' & 'Commission Financo' both are using the same logic to be set using the first 4 fields (upper part of the screenshot). Commission Makelaar has the mask enable, while the right doesn't.

![CleanShot 2024-05-30 at 18 04 33@2x](https://github.com/ariaieboy/filament-currency/assets/26650855/9850300a-5267-4840-8a1e-7a7a3ec41a6c)

### How to reproduce the bug

```
// Field on updated currency field (full_commission_amount) on afterStateUpdate
   \Filament\Forms\Components\TextInput::make('commission_percentage')
      ->afterStateUpdated(fn(Forms\Get $get, Forms\Set $set) => self::updateProjectCalculations($set, $get))
// here the $set value can't be seen
\Filament\Forms\Components\TextInput::make('full_commission_amount')
 ->numeric()
 ->currencyMask()
```

### Package Version

1.7.4

### PHP Version

8.2

### Laravel Version

11.4

**Comment by ariaieboy** [comment]
if you create a public repo that contains the minimum code to reproduce this bug I can debug it faster you can use my https://github.com/ariaieboy/filament-dev-env repo to create a reproducible enviroment

**Comment by quinleys** [comment]
Alright, give me 5 minutes. I will give you a repo. Thanks!

**Comment by quinleys** [comment]
Here you go, https://github.com/quinleys/filament-currency-bug

**Comment by ariaieboy** [comment]
https://github.com/ariaieboy/filament-currency/releases/tag/1.7.5 
test 1.7.5 it should be fixed
