### ISSUE TITLE
[Feature]: Add possibility for live(onBlur: true)

### ISSUE THREAD

**Issue by nielsvh2103** [ariaieboy/filament-currency#34]
### What happened?

Not really a bug, just not implemented. 

onBlur: true in live() would be handy if we can use this with currencyMask.

It would be nice to not just always let it be reactive but have a choice for onBlur aswell.

### How to reproduce the bug

Just add live(onBlur: true) it won't work.

I am creating a PR to introduce this, though im having a few issues :)

### Package Version

1.7.5

### PHP Version

8.3.7

### Laravel Version

11.9

### Which operating systems does with happen with?

macOS

**Comment by ariaieboy** [comment]
added in [v1.8.0](https://github.com/ariaieboy/filament-currency/releases/tag/1.8.0)
