### ISSUE TITLE
[Bug]: field is required on safari error

### ISSUE THREAD

**Issue by ziming** [ariaieboy/filament-currency#43]
### What happened?

enter a form with this field say 18000 , press submit. it will say field is required. only happen on safari

### How to reproduce the bug

enter a form with this field, press submit. it will say field is required. only happen on safari

I have downgraded all the way from 1.9.0 to 1.8.1 and it still happen on safari according to customers

### Package Version

1.8.1 to 1.9.0

### PHP Version

8.3

### Laravel Version

11

### Which operating systems does with happen with?

macOS

### Notes

also happen on safari mobile according to site users

**Comment by ariaieboy** [comment]
create a repo that reproduces this bug so I can test it.
It only shows an error on macOS Safari
can you also test ios safari?

**Comment by ziming** [comment]
i don't have iPhone sorry

**Comment by ariaieboy** [comment]
I tested on ios safari and I couldn't reproduce this bug.
You need to share a public repo with the minimum code required to reproduce this bug.

**Comment by ziming** [comment]
did u try a number big enough have auto comma like 18,000 ?

sample code

```php
TextInput::make('amount')
                        ->label('Amount')
                        ->integer()
                        ->minValue(500)
                        ->maxValue(8_000_000_000)
                        ->currencyMask(precision: 0)
                        ->required(),
```

**Comment by ariaieboy** [comment]
test version 1.9.1 and let me know if this issue is fixed or not
