### ISSUE TITLE
[Bug]: MONEY_DEFAULTS_CONVERT env option is not being used

### ISSUE THREAD

**Issue by jwhoami** [ariaieboy/filament-currency#45]
### What happened?

According to the config file, I can set MONEY_DEFAULTS_CONVERT in my env file. However this setting has no effect.

I am storing the amount in the db as 100.00

If I use it on a table column like this

```
        Tables\Columns\TextColumn::make('amount')
          ->currency(),
```

It outputs $1.00

If I change the shouldConvert option to true
```
        Tables\Columns\TextColumn::make('amount')
          ->currency(shouldConvert: true),
```

It outputs $100.00, which is what I want.

However to setting the MONEY_DEFAULTS_CONVERT=true and removing the shouldConvert option

```
        Tables\Columns\TextColumn::make('amount')
          ->currency(),
```

It outputs $1.00 instead of $100.00

Can you please apply an update which respects the MONEY_DEFAULTS_CONVERT env variable.

Thanks for this package.

### How to reproduce the bug

```
        Tables\Columns\TextColumn::make('amount')
          ->currency(),
```

It outputs $1.00 instead of $100.00 even when MONEY_DEFAULTS_CONVERT env variable is set to true.

### Package Version

1.9

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

Linux

**Comment by ariaieboy** [comment]
added in 1.10.0
