### ISSUE TITLE
[Bug]: Error casting int column database

### ISSUE THREAD

**Issue by danielreales7** [ariaieboy/filament-currency#5]
### What happened?

I am working with a TextInput where I want to display the price in EUR, and the value coming from the database is of integer type. When I apply ->currencyMask(thousandSeparator: '.', decimalSeparator: ',', precision: 2), it gives me an error in the console:
![image](https://github.com/ariaieboy/filament-currency/assets/5383214/b12a58fa-8344-4f85-9c6b-a3a72c72ca70)

I'm using this casting:

https://filamentphp.com/docs/3.x/panels/getting-started#casting-the-price-to-an-integer

### How to reproduce the bug

`TextInput::make('price')
                    ->required()
                    ->numeric()
                    ->suffix('€')
                    ->currencyMask(thousandSeparator: '.',decimalSeparator: ',',precision: 2)`

### Package Version

1.1.1

### PHP Version

8.1

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by danielreales7** [comment]
If I delete the casting that I created the TextColumn works fine for me:
`TextColumn::make('price')->label('Precio')->currency('EUR')` but `TextInput` have the same error in console. I'm testing in Chrome

**Comment by ariaieboy** [comment]
@danielreales7, can you create a public repo that reproduces this bug so I can investigate the problem?

**Comment by danielreales7** [comment]
@ariaieboy [https://github.com/danielreales7/test-filament-currency](url) I create a new project for this with a seeder.

Thank you so much for your help!

**Comment by danielreales7** [comment]
@ariaieboy I think you have to use [https://alpinejs.dev/magics/nextTick](url) when import dynamic mask on `x-init`

**Comment by ariaieboy** [comment]
@danielreales7 test version 1.1.2, the problem should be fixed

**Comment by danielreales7** [comment]
Hi @ariaieboy 

I'm getting same error:

![image](https://github.com/ariaieboy/filament-currency/assets/5383214/b478075c-7a18-41eb-b2f0-4a5b9550406b)

`replaceAll` for number input it's not possible.

**Comment by ariaieboy** [comment]
> Hi @ariaieboy
> 
> I'm getting same error:
> 
> ![image](https://user-images.githubusercontent.com/5383214/275292165-b478075c-7a18-41eb-b2f0-4a5b9550406b.png)
> 
> `replaceAll` for number input it's not possible.

can you test it in your repo and reproduce this error on that?
[https://github.com/danielreales7/test-filament-currency](https://github.com/ariaieboy/filament-currency/issues/url)

**Comment by ariaieboy** [comment]
fixed in [1.1.3](https://github.com/ariaieboy/filament-currency/releases/tag/1.1.3)
