### ISSUE TITLE
[Bug]: Losing live attribute when using currencyMask

### ISSUE THREAD

**Issue by danielreales7** [ariaieboy/filament-currency#8]
### What happened?

When you use the `->currencyMask` attribute you lose the `->live` attribute

Without `->currencyMask()`
![image](https://github.com/ariaieboy/filament-currency/assets/5383214/399d25e7-0ae8-45ab-982d-91975e6a4f2a)

With `->currencyMask()`
![image](https://github.com/ariaieboy/filament-currency/assets/5383214/8049efc8-f60e-4785-b1c0-3a7397bb98f9)

### How to reproduce the bug

When you use the `->currencyMask` attribute you lose the `->live` attribute

### Package Version

1.1.3

### PHP Version

8.1

### Laravel Version

10.10

**Comment by ariaieboy** [comment]
We are using the internal filamentpho methods to create our input entangle according to your screenshots the code that genretade passes true as the second option of the entangle that means that the data must be synced live with backend 
Here is the livewire documentation
https://livewire.laravel.com/docs/javascript

If the value is not updating you should create an issue in livewire repository

**Comment by danielreales7** [comment]
@ariaieboy It syncs well with the backend but I need it to have a debounce of 500 and it doesn't work.

**Comment by ariaieboy** [comment]
Dis you set the denounce amount in the live method 
https://filamentphp.com/docs/3.x/forms/advanced#debouncing-reactive-fields

**Comment by ariaieboy** [comment]
We currently use Filament `applyStateBindingModifiers` helper to create our state binding modifiers. 
Since Livewire doesn't have the option to change the debounce amount in the `entangle` method the debounce amount is not used in entangled fields for example the filament markdown editor does not support debouncing too.

**Comment by danielreales7** [comment]
@ariaieboy It's curious. I didn't know that. Thank you also for the help, but for example if I want to calculate a price refund automatically when the user writes the quantity, if the user writes too quickly errors occur and the calculation is not done correctly. That's why I wanted to use debounce.

**Comment by ahmetkocabiyik** [comment]
Same problem i have. If i use live method in any form element to update price field can't use currenyMask method. If you solve this it will be great.

**Comment by ariaieboy** [comment]
> Same problem i have. If i use live method in any form element to update price field, can't use currenyMask method in price input. If you solve this it will be great.

What is the error ?
Create a repo and reproduce the problem
